#!/bin/sh
rescue_shell() {
    echo "Something went wrong. Dropping to a shell."
}

mount -t proc proc /proc
mount -t sysfs sysfs /sys
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
#mount -t devtmpfs none /dev
mount -t devtmpfs devtmpfs /dev
#mkdir /dev/pts
#mount -t devpts devpts /dev/pts

# Mount the root filesystem.
#mount -o ro /dev/sda1 /mnt/root || rescue_shell


exec sh

